### ISSUE TITLE
Inconsistent return values for excluded test results.

### ISSUE THREAD

**Issue by helske** [ropensci-review-tools/autotest#53]
I wanted  to test only one function with a specific test in my package, and after fixing an error by #52 proceeded as follows:

```
x <- autotest_package(test = FALSE, functions = "ar1_ng")
x$test <- FALSE # all tests off
x$test[x$test_name == "return_desc_includes_class"] <- TRUE # test only return object
z <- autotest_package(test = TRUE, functions = "ar1_ng", test_data = x)
```
I expected to get a tibble consisting of only (failed) tests related to `return_desc_includes_class`, but looking at the results I see several extra cases with `test = TRUE`:

```
> z[z$test == TRUE,]
# A tibble: 21 x 9
   type       test_name                  fn_name parameter       parameter_type   operation            content                             test  yaml_hash     
   <chr>      <chr>                      <chr>   <chr>           <chr>            <chr>                <chr>                               <lgl> <chr>         
 1 error      NA                         ar1_ng  NA              NA               normal function call object of type 'symbol' is not sub~ TRUE  aa0134814e53f~
 2 warning    par_matches_docs           ar1_ng  sigma           NA               Check that document~ Parameter documentation does not d~ TRUE  aa0134814e53f~
 3 warning    par_matches_docs           ar1_ng  phi             NA               Check that document~ Parameter documentation does not d~ TRUE  aa0134814e53f~
 4 diagnostic return_desc_includes_class ar1_ng  (return object) (return object)  Check whether descr~ Function [ar1_ng] returns a value ~ TRUE  aa0134814e53f~
 5 dummy      int_range                  ar1_ng  mu              single integer   Ascertain permissib~ Should either be unrestricted or c~ TRUE  aa0134814e53f~
 6 no_test    single_char_case           ar1_ng  distribution    single character lower-case characte~ (Should yield same result)          TRUE  716b92db2978f~
 7 no_test    single_char_case           ar1_ng  distribution    single character upper-case characte~ (Should yield same result)          TRUE  716b92db2978f~
 8 no_test    random_char_string         ar1_ng  distribution    single character random character st~ Should error                        TRUE  716b92db2978f~
 9 no_test    single_par_as_length_2     ar1_ng  distribution    single character Length 2 vector for~ Should trigger message, warning, o~ TRUE  716b92db2978f~
10 no_test    return_successful          ar1_ng  (return object) (return object)  Check that function~ NA                                  TRUE  716b92db2978f~
# ... with 11 more rows
```
However, checking only cases where `type` is not `dummy` or `no_test` it seems that only the tests defined in `test_data` are actually run (in addition to some new warnings and an error which I don't quite understand):
```
> z[z$test == TRUE & !(z$type %in% c("dummy", "no_test")),]
# A tibble: 4 x 9
  type       test_name                  fn_name parameter       parameter_type  operation             content                              test  yaml_hash     
  <chr>      <chr>                      <chr>   <chr>           <chr>           <chr>                 <chr>                                <lgl> <chr>         
1 error      NA                         ar1_ng  NA              NA              normal function call  object of type 'symbol' is not subs~ TRUE  aa0134814e53f~
2 warning    par_matches_docs           ar1_ng  sigma           NA              Check that documenta~ Parameter documentation does not de~ TRUE  aa0134814e53f~
3 warning    par_matches_docs           ar1_ng  phi             NA              Check that documenta~ Parameter documentation does not de~ TRUE  aa0134814e53f~
4 diagnostic return_desc_includes_class ar1_ng  (return object) (return object) Check whether descri~ Function [ar1_ng] returns a value o~ TRUE  aa0134814e53f~
```
Looking into the source codes, it seems that the behaviour of tests is a bit inconsistent in terms of return value when the test does not run. For example, in case of `trivial_noise` test the return value is `dbl_noise_dummy_report (x)` (which leaves `test = TRUE` and `type = dummy`), whereas `test_vec_class_defs`changes these to `FALSE` and `no_test`. I guess this might not matter in practice, other than being potentially confusing when looking at the results.

**Comment by mpadge** [comment]
Great catch @helske! The problem here is a conflict which I had not thought about: Tests can be individually switched on and off via `test_data`, but then there's also a definitely global `test = TRUE` parameter. The latter is ultimately granted primacy here through first constructing an `autotest_object` with `test = TRUE`:
https://github.com/ropensci-review-tools/autotest/blob/45f7c4cd36c3642c1b99aa076e307167d867fa63/R/autotest-functions.R#L106-L115

And then only subsequently passing through `test_data` to determine whether individual tests have been switched on or off:
https://github.com/ropensci-review-tools/autotest/blob/45f7c4cd36c3642c1b99aa076e307167d867fa63/R/autotest-functions.R#L123-L131

The latter then has no effect, because the former "global" setting has already over-ridden those. This clearly makes no sense.  The problem is then really pervasive, because most code then works like this:

https://github.com/ropensci-review-tools/autotest/blob/45f7c4cd36c3642c1b99aa076e307167d867fa63/R/test-rect-methods.R#L130-L138

`x` is the `autotest_obj`, so the global value of `test` overrides the local settings from `test_data`.  I'll ponder how best to rectify this and let you know. I'll also already list you as a contributor because your debugging work has been really helpful. If you're interested in boosting your publicly visible number of contributions here, then please feel free to address this via a PR. To that end, I might start addressing it via a branch and ping you there to see whether you want to contribute more. Thanks!

**Comment by mpadge** [comment]
Sorry, actually not quite right there - it's been too long since i really immersed myself in this code :smile:. There is already a [`test_these_data()` function](https://github.com/ropensci-review-tools/autotest/blob/main/R/test-data.R) that is used to override the global flag. Your code highlights that there are still some gaps in applying this function throughout. I've started addressing remaining gaps in a new branch

**Comment by mpadge** [comment]
@helske The above commits fix the inconsistencies in the return results. Note also that lots of other commits in the meantime have improved the matching of parameter & return value descriptions, so `ar1_ng` generates fewer diagnostic messages, and none for "return_desc_includes_class". The following shows what happens for one of the few remaining tests that does generate messages:

``` r
library (autotest)
package <- "/<path>/<to>/bssm"

x <- autotest_package(package, test = FALSE, functions = "ar1_ng")
#> ℹ Loading bssm
```

    #> 
    #> ── autotesting bssm ──
    #> 
    #> ✔ [1 / 2]: ar1_ng
    #> ✔ [2 / 2]: ar1_ng


``` r
x$test <- FALSE # all tests off
x$test[x$test_name == "int_as_numeric"] <- TRUE
z <- autotest_package(package, test = TRUE, functions = "ar1_ng", test_data = x)
#> ── autotesting bssm ──
#> 
#> ✔ [1 / 2]: ar1_ng
#> ✔ [2 / 2]: ar1_ng

table (z$type)
#> 
#> diagnostic    no_test 
#>          3         35
```

<sup>Created on 2021-09-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

The 3 diagnostic messages are all for

> Function [ar1_ng] returns different values when parameter [u] only demontrated or documented as int-valued is submitted as double

The only remaining issue here is that all of the `no_test` results are returned as well, but it would make more sense to remove all of those, to ensure that `autotest_package()` can still return `NULL` when all tests which are switched on actually succeed. Next commit will do that.
