### ISSUE TITLE
UTF-8 encoding on Windows garbles Rd files

### ISSUE THREAD

**Issue by helske** [ropensci-review-tools/autotest#54]
In `get_Rd_value`, the return value of the function is obtained by converting the Rd to txt file with `tools::Rd2txt (rd, out = f, outputEncoding = "UTF-8")` which is then used to find the return type. However, on my Windows 10 using `outputEncoding = "UTF-8" messes up the text surrounded by `\code{}` in the Rd file:

```
tools::Rd2txt("man/ar1_ng.Rd", outputEncoding = "UTF-8")
...
Value:

     Object of class â€˜ar1_ngâ€™.
....
```
Without defining the `outputEncoding` the text is rendered correctly (Object of class ‘ar1_ng’) both Windows as well on Linux. I have UTF-8 defined both in Rstudio and in package DESCRIPTION, and also tested changing `options(encoding)` to UTF-8 in `.Rprofile so Rd files are generated as UTF-8 without a difference.

**Comment by mpadge** [comment]
Thanks @helske for the helpful observation. The forced encoding was because CRAN enforces UTF-8 anyway, so any CRAN package should not experience that issue. But of course `autotest` should be general enough to be used anywhere, including on packages/systems with other local encodings. Particularly in that case, all that is needed is to get a character label for the class, and as long as that remains fixed on a machine there should be no problem dropping the forced `outputEncoding`. It's also high time that your contributions here starting being in more concrete pull-request form, if you're willing, so please submit a PR changing to `outputEncoding = ""` and add a comment referencing this issue, along with a note that the value of "" will deliver the result in the system-native encoding. Thanks!
