### ISSUE TITLE
How to deal with 'Custom class definitions for vector input'?

### ISSUE THREAD

**Issue by christophsax** [ropensci-review-tools/autotest#56]
I don't fully understand the 'Custom class definitions for vector input' complains. Some of my arguments need to be of a certain class, and I test for that in the function. autotest tries to feed it with a vector, and the function fails, as it should. What can I do to make autotest happy?

```r
# remotes::install_github("christophsax/tsbox", ref = "autotest")

library(autotest)
library(tsbox)
a <- autotest_package(functions = "ts_span", test = TRUE)
a$operation
a$operation
#> [1] "Custom class definitions for vector input"
a$content
#> [1] "Function [ts_span] errors on vector columns with different classes when # submitted as template Error message: :quote(structure(c(5, 3, 0, 2, 0, 3, 2, 3, 6, : ts_boxable(template) is not TRUE"
```

autotest tries to run is something like this:

```r
ts_span(mdeaths, template = c(5, 3, 0, 2))
#> Error in ts_span(mdeaths, template = c(5, 3, 0, 2)) : 
#>   ts_boxable(template) is not TRUE
```

`template` must be a ts-boxable object, an object of class `ts`, `xts`, `zoo`, `data.frame`, `data.table`, `tbl`, `tbl_ts`, `tbl_time`, `tis`, `irts` or `timeSeries`. It makes no sense to provide it as a vector.

**Comment by mpadge** [comment]
Huh, wow! That's because the identification as a vector relies on `is.atomic`. I was relying on the [description of that function](https://stat.ethz.ch/R-manual/R-devel/library/base/html/is.recursive.html) that:

> is.atomic is true for the atomic types ("logical", "integer", "numeric", "complex", "character" and "raw") and NULL. 

But of course a class can be imposed on something which still retains `is.atomic()`, as for `ts` objects. The man entry for vector [makes this a bit clearer](https://stat.ethz.ch/R-manual/R-devel/library/base/html/vector.html) in stating only,

> The atomic modes are "logical", "integer", "numeric" (synonym "double"), "complex", "character" and "raw". 

The phrase "atomic modes" makes it more clear there what's going on - it's only a check for storage mode, and is not related to class structures of anything else.  This all comes down to the function used to identify whether a parameter is a vector or not:

https://github.com/ropensci-review-tools/autotest/blob/4e831f5a5929581c9ec94c7b38f983b60da69c5c/R/function-param-types.R#L59-L67

My original thought was to permit a range of (unknown) class objects to be identified as vectors, but since, for example, [`vctrs` objects](https://vctrs.r-lib.org) are themselves not `vectors`, this is potentially of little use. I could just modify the function to reject anything with a class definition as being a vector? That would definitely fix your issue here.

**Comment by christophsax** [comment]
Thanks! 

Ah, I see now how it works: If I had used an example that uses, e.g., an `xts`, rather than a `ts`, in the example, it would not complain. But single `ts` objects are seen as vectors by the definition above. 

Yes, rejecting objects with a class would solve my problem. Not clear to me for which class objects it would make sense to to substitute them by a simple numeric vector, but for `ts`-objects, is is probably something to avoid. After all, the standards recommend packages not to allow it:

> **TS1.0** Time Series Software should use and rely on explicit class systems developed for representing time series data, and should not permit generic, non-time-series input

**Comment by helske** [comment]
I got bitten by this same issue and agree that it is probably the clearest option to just reject anything with a class. 

However, there seems to be other related issue concerning the calling function `get_param_types`, i.e.
>
> https://github.com/ropensci-review-tools/autotest/blob/4e831f5a5929581c9ec94c7b38f983b60da69c5c/R/function-param-types.R#L12-L23
>

I don't understand what lines are supposed to 19-22 do, but in my case, it switches custom `bssm_prior` objects (which are essentially lists with custom lass attribute) to vectors. 

This is the example:
```
set.seed(1)
mu <- 2
rho <- 0.7
sd_y <- 0.1
sigma <- 0.5
beta <- -1
x <- rnorm(30)
z <- y <- numeric(30)
z[1] <- rnorm(1, mu, sigma / sqrt(1 - rho^2))
y[1] <- rnorm(1, beta * x[1] + z[1], sd_y)
for(i in 2:30) {
  z[i] <- rnorm(1, mu * (1 - rho) + rho * z[i - 1], sigma)
  y[i] <- rnorm(1, beta * x[i] + z[i], sd_y)
}
model <- ar1_lg(y, rho = uniform(0.5, -1, 1), 
  sigma = halfnormal(1, 10), mu = normal(0, 0, 1), 
  sd_y = halfnormal(1, 10), 
  xreg = x,  beta = normal(0, 0, 1))
```

Inside `get_param_types`:
```
> param_types
[1] "vector" NA       NA       NA       NA       "vector" NA  
> par_lengths
      fn   par single
1 ar1_lg  beta  FALSE
2 ar1_lg    mu  FALSE
3 ar1_lg   rho  FALSE
4 ar1_lg  sd_y  FALSE
5 ar1_lg sigma  FALSE
6 ar1_lg  xreg  FALSE
7 ar1_lg     y   TRUE
> index
[1] 1 2 3 4 5 6
```
So now everything is a vector:
```
> param_types
[1] "vector" "vector" "vector" "vector" "vector" "vector" "vector"
```
Although I'm not sure if this is the actual reason for this behaviour, the `single` column looked suspicious (y is and x are vectors but `y` is declared as single while `x` is not), so I went looking what happens in function `single_or_vec`, which creates `par_lengths`:
>
> https://github.com/ropensci-review-tools/autotest/blob/4e831f5a5929581c9ec94c7b38f983b60da69c5c/R/function-param-types.R#L91-L107
>

I think the issue is due to the `eval` call, as it tries to evaluate `ij` in the current environment, so `normal(0,0,1)` will be evaluated correctly as `bssm_prior` object of length 4, but evaluating `y` throws an error as such variable is not found in the clean R session (leading to `single=TRUE`), and same with `x`, except in my case I had run `autotest_package` earlier so I had `x` as a `test_data` `data.frame` in my calling environment which was found by `eval` so `single=FALSE`.

**Comment by mpadge** [comment]
Thanks @helske: that issue was the same as #51,  where the `eval` needed to be changed to be called in the package namespace environment, exactly as you suggested. The intermediate values you showed above are now:
``` r
> param_types
[1] "vector"  "vector"  "vector"  "vector"  "vector"  "vector"  "vector"
> par_lengths
      fn   par single
1 ar1_lg  beta  FALSE
2 ar1_lg    mu  FALSE
3 ar1_lg   rho  FALSE
4 ar1_lg  sd_y  FALSE
5 ar1_lg sigma  FALSE
6 ar1_lg  xreg  TRUE
7 ar1_lg     y  TRUE
```
And all parameters are all still identified as vectors, but now for the correct reasons. `xreg` has `single = TRUE` is `par_lengths` because it is a name object (`x`), but when that value is evaluated it now correctly associates it with `rnorm(30)`, so `param_types` is "vector". Similarly, `y` is also a name, so `par_length$single` is `TRUE`, but it's value is `y` which is a numeric vector of length 30, so also "vector". Does that make sense now?

**Comment by mpadge** [comment]
Thanks to both of you for input here. That commit should address all of your concerns by ensuring that class definitions grabbed from evaluating example code are used to restrict class mutations, and in particular are used to ensure that anything that is vector-like yet has a non-atomic class is *not* mutated. (Note that I'm not particularly happy with the whole workflow surrounding the code changed in the above commits, but most of the mess will soon be completely refactored anyway to avoid the current hand-parsing approach.)

**Comment by christophsax** [comment]
Thanks! I guess I still have a problem here.

When I process this mini function, it still tries to substitute the `ts` by a vector. What do I miss?

```r
#' Function that likes ts
#' @param x `ts`
#' @return `ts`
#' @export
#' @examples
#' ts_fun(discoveries)
ts_fun <- function(x) {
  stopifnot(inherits(x, "ts"))
  x
}
```

```
library(autotest)
ans <- autotest_package(".", functions = "ts_fun", test = TRUE)
ans$content
#> [1] "Function [ts_fun] errors on vector columns with different classes when submitted as x Error message: :quote(structure(c(5, 3, 0, 2, 0, 3, 2, 3, 6, : inherits(x, \"ts\") is not TRUE"

packageVersion("autotest")
#> [1] ‘0.0.2.154’
```

**Comment by mpadge** [comment]
Sorry Christoph - I had neglected to pass the class definitions now extracted from example code through to the test controls, to ensure they weren't mutated. Now done, so testing `ts_fun` returns `NULL`.
