### ISSUE TITLE
return value may be one of several classes?

### ISSUE THREAD

**Issue by christophsax** [ropensci-review-tools/autotest#58]
autotest checks the return value in the documentation to learn what object to expect. Many of my functions return whatever is fed into them, this may be any ts-boxable time series, an object of class `ts`, `xts`, `zoo`, `data.frame`, `data.table`, `tbl`, `tbl_ts`, `tbl_time`, `tis`, `irts` or `timeSeries`. 
Is it possible to specify multiple classes for the return value of the documentation?

**Comment by mpadge** [comment]
It currently only checks for a match between any one of the return classes and any entry in the documentation. But yeah, in your case it obviously can't be expected that you specify all possible return values in documentation, meaning any one of these may fail. In other words: Current answer to your question is that you'd have to specify **all** possible return classes in your documentation to pass tests there. Two alternatives spring to mind:

1. Use `test_data` to switch off calls which fail this test. This can also be combined with the [`testthat` expectations](https://github.com/ropensci-review-tools/pkgcheck/blob/e084f822b1725480fcecc81ce60d24dadf124d28/R/format-checks.R#L65-L71) to ensure your tests pass. I admit in this case that that is not very satisfactory!
2. Modify `autotest` so that if any call to the `"return_class_matches_desc"` passes then all should pass

The second option would be a possibility, but would you have any suggestions for other ways to resolve this?

**Comment by christophsax** [comment]
Listing all possible classes is perfectly fine, I just wasn't aware that this is sufficient. Also, thanks to `@inherits`, it is not too cumbersome to do.

Thanks!
