### ISSUE TITLE
Add desc min version to DESCRIPTION?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/autotest#74]
Even if the issue was just related to pkgdown website building?

**Comment by mpadge** [comment]
Can't currently be done, because the `desc` package is not directly used, so there is no way to specify a min version; it's only listed as a `remote`, which can only be used to install latest github version, but can't be used to control version. I'll keep this issue open until CRAN version is updated beyond 1.4.0, then remove the `remotes` line.
