### ISSUE TITLE
eternally-running calculations in autotest

### ISSUE THREAD

**Issue by abigailkeller** [ropensci-review-tools/autotest#88]
Hi!
I'm reaching out because I am building an [R package](https://github.com/abigailkeller/eDNAjoint/tree/master) intended to submit to ROpenSci, and for a few of my functions, running autotest_package() runs "indefinitely" without producing outputs. By "indefinitely", I mean it does not complete in <8 hours.

The main function in my package is [jointModel()](https://github.com/abigailkeller/eDNAjoint/blob/master/R/jointModel.R), which passes autotest in ~30 min on my machine. Other functions in the package are used to help interpret outputs from jointModel, and these are the functions that run indefinitely. (For example, [detectionCalculate()](https://github.com/abigailkeller/eDNAjoint/blob/master/R/detectionCalculate.R). and [detectionPlot()](https://github.com/abigailkeller/eDNAjoint/blob/master/R/detectionPlot.R)). 

I'm wondering if there is something off about the way that I am setting up the examples? Or should I expect that the autotest should just take a long time based on the nature of the function's parameters?

**Comment by mpadge** [comment]
Those two functions you describe have examples wrapped in `\donttest`, and so are entirely ignored by `autotest`. I see this:

``` r
library (autotest)
package <- "/<local>/<path>/<to>//eDNAjoint"
devtools::load_all (package) # So system.time excludes that
#> ℹ Loading eDNAjoint
system.time (
  res <- autotest_package (package, test = TRUE, functions = c ("detectionCalculate", "detectionPlot"))
)
#> 
#> ── autotesting eDNAjoint ──
#>    user  system elapsed 
#>   0.178   0.006   0.190
res
#> NULL
```

<sup>Created on 2024-04-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

And `autotest_package` returns `NULL` as expected.

**Comment by abigailkeller** [comment]
@mpadge Thanks for your response. I have quite a few follow-up questions if that's alright. Thanks so much for your help!

1. I wrapped the examples in donttest{} because my functions run MCMC, and the examples should take >5 seconds to run (which I think will break `R CMD check`?). When I run `autotest_package()` locally, it still produces output. See below. But if I run the function as a background job in RStudio, it produces `NULL` like you observe. Do you know why that might be?
<img width="569" alt="Screenshot 2024-05-04 113132" src="https://github.com/ropensci-review-tools/autotest/assets/62615943/3adf3cc6-a322-4718-a26d-fef63181a680">

2. I've found that running the `int_range` test on some of my functions causes the session to crash, particularly for parameters that control the MCMC sampling (i.e., number of MCMC chains, MCMC iterations). Do you have suggestions for how to manage this problem?

3. Should we ensure that all our functions pass autotest before submitting to ROpenSci? For example, for the below `negate_logical` test, the function should produce an error if `q = TRUE` and another input parameter does not have associated content. I have created the below input check that produces an error for the user if this combination happens. Is there any flexibility with making sure our functions pass all the tests before submitting?
<img width="684" alt="Screenshot 2024-05-13 122421" src="https://github.com/ropensci-review-tools/autotest/assets/62615943/1383f3d9-59c4-46a1-ab7b-cb226a242db6">

4. If running `autotest_package()` with `test = TRUE` returns rows with type = diagnostic, is this something we should be addressing? I'm finding that these are often tests with content `(Function call should still work unless explicitly prevented)`. What does it mean for the return type to be diagnostic?

**Comment by mpadge** [comment]
@abigailkeller Thank you for your deep engagement with autotest results. The most important thing for you to be aware of is that autotest is *recommended* only, and not *required*. That means you are free to ignore any and all aspects which you feel can or should be ignored, or even which you simply don't understand.

(Longer story there is that development of autotest is unfortunately stalled, awaiting further funding ...)

Some specific responses to your questions now follow:

----

>  1. I wrapped the examples in donttest{} because my functions run MCMC, and the examples should take >5 seconds to run (which I think will break `R CMD check`?). When I run `autotest_package()` locally, it still produces output. See below. But if I run the function as a background job in RStudio, it produces `NULL` like you observe. Do you know why that might be?

That one I do not know. autotest ignores any code wrapped in `donttest`, so should produce no output. And your reasoning about running times is indeed correct. More importantly, MCMC simulations are generally done in parallel, and this will generally fail CRAN checks, so `donttest` is the way to go there.

>   2. I've found that running the `int_range` test on some of my functions causes the session to crash, particularly for parameters that control the MCMC sampling (i.e., number of MCMC chains, MCMC iterations). Do you have suggestions for how to manage this problem?

That behaviour is system dependent. If you're on Linux, the best way is to start R with a `ulimit` value to define max amount of memory that will be allocated. It will then simply stop any process which exceed that, rather than crashing R itself. How to do that also depends on how you're running R, but an answer should be easy to find. Other OS's are beyond my knowledge, alas.

>   3. Should we ensure that all our functions pass autotest before submitting to ROpenSci? For example, for the below `negate_logical` test, the function should produce an error if `q = TRUE` and another input parameter does not have associated content. I have created the below input check that produces an error for the user if this combination happens. Is there any flexibility with making sure our functions pass all the tests before submitting?

Not at all. autotest is intended only as an aid to improve your code, and not as a requirement. Just ignore such instances.

>   4. If running `autotest_package()` with `test = TRUE` returns rows with type = diagnostic, is this something we should be addressing? I'm finding that these are often tests with content `(Function call should still work unless explicitly prevented)`. What does it mean for the return type to be diagnostic?

That's intended just as a class of "helpful" messages. The important classes are "error" and "warning", while "diagnostic" flags aspects you may like to consider, but may also ignore.

---

Hope that helps, and as always, feel free to ask any more questions you may have, or to close this issue once you're happy with the autotest results.

**Comment by abigailkeller** [comment]
@mpadge Thanks so much for such a detailed response. I really appreciate it! The package has been super useful in helping me understand my package's behavior in response to unexpected inputs. It's not passing all checks, but I think I will submit regardless.

Thanks again!

**Comment by mpadge** [comment]
Great to see you've submitted! Looking forward to seeing your package progress through peer-review, and improve as it does so. All the best!
